language: c 
os:
 - linux
 - osx

sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
    - common_py_deps="jinja2 conda-build"
    - PACKAGENAME=pyemma
    - ORGNAME=omnia
    - secure: BBcvn2SDTrKtCQdJFJ6ezv5lmYWYtoukS1maptS2RuEHrBqVMN++go5U9BTNDHBLUESewolaR9GFng2xXBLpPYgCE2XOGsJPKM0L15/Ae/QWSmqUbLNJFVZz3I3EliJJV9si1EaWQnQY0axPqSXRTA8CyVOeO9zxMewWozGIHE0=
  matrix:
    # minimum possible numpy version = 1.8, because of mdtraj
    - python=2.7  CONDA_PY=27  CONDA_NPY=19
    - python=2.7  CONDA_PY=27  CONDA_NPY=110
    - python=3.4  CONDA_PY=34  CONDA_NPY=19
    - python=3.5  CONDA_PY=35  CONDA_NPY=110

# exclude too verbose configs on osx, since these are dead slow.
matrix:
   exclude:
     - os: osx
       env: python=3.4  CONDA_PY=34  CONDA_NPY=19
     - os: osx
       env: python=2.7  CONDA_PY=27  CONDA_NPY=19

before_install:
- devtools/ci/travis/install_miniconda.sh
- conda config --set always_yes true 
- conda config --add channels omnia 
- conda install -q $common_py_deps 

script:
- conda build -q devtools/conda-recipe

after_success:
# coverage report: needs .coverage file generated by testsuite and git src
- pip install coveralls
- coveralls 
- if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then source devtools/ci/travis/after_success.sh; fi
