language: c
git:
  submodules: false
  depth: 500
os:
 - osx
 - linux

sudo: false

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
    - PYTHONHASHSEED=0
    - OMP_NUM_THREADS=2
    - PYEMMA_NJOBS=1
    - MACOSX_DEPLOYMENT_TARGET=10.9
    - PIP_INSTALL=NO
  matrix:
    - CONDA_PY=3.5
    - CONDA_PY=3.6
    - CONDA_PY=3.7

matrix:
  exclude: # test only 3.7 on osx.
    - env: CONDA_PY=3.5
      os: osx
    - env: CONDA_PY=3.6
      os: osx
  include:
    - env: CONDA_PY=3.7 PIP_INSTALL=YES
      os: linux


before_install:
- "[ ${PIP_INSTALL} = NO ] && source devtools/ci/travis/install_miniconda.sh"

script:
- "[ ${PIP_INSTALL} = NO ] && conda build -q devtools/conda-recipe -c conda-forge"
- "[ ${PIP_INSTALL} = YES ] && pip3 install . -v"

after_script:
- bash <(curl -s https://codecov.io/bash) -f $HOME/coverage.xml -e CONDA_PY
