language: python
python:
# - 2.6
 - 2.7

env:
  global:
    - PATH=$HOME/miniconda/bin:$HOME/miniconda/envs/ci/bin/:$PATH
    - common_py_deps="pip nose"
    - doc_deps="ipython sphinx matplotlib numpydoc pyzmq"
  matrix:
    - deps="scipy=0.11 numpy=1.7"
#    - deps="scipy=0.11 numpy=1.7 cython"
# - deps="numpy=0.12 numpy=1.8" 
# - deps="numpy=0.13 numpy=1.8" 
# - deps="numpy=0.14 numpy=1.9" 
# - deps="scipy=0.11 numpy=1.6"

before_install:
- deactivate # travis python venv
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O mc.sh -o /dev/null
- bash mc.sh -b
- conda create -q --yes -n ci python=$TRAVIS_PYTHON_VERSION $deps $common_py_deps
- source activate ci
- python -c "import scipy; print scipy.__version__; print scipy.__numpy_version__"

install:
- python setup.py install

script:
- python setup.py test 

after_success:
- tools/ci/make_docs.sh

deploy:
  provider: pypi
  distributions: "sdist upload_docs"
  skip_cleanup: true
  docs_dir: doc/build/html
  user:
    secure: "DJtsbUhAc/bkUOt8LBxZPzxUonZBQEWsxqKzqVoKoj+SgsILWwsijn0ENHYO61na36r3iBiMNW7JrSkBk/Z8BmRtW27mE2eZJ7ztzuDVu/MKlR47e1QTuDfFM/DqtmjuXEBPDmP/V8B9MMTuM05ov1GCa1q1tvcu5dtWeYRM78I="
  password:
    secure: "FFbvO0jJFG7Ib1JNPm5TFgmEKNUdJ/2+n+1RP2bLAAi2ZY/i+1T+2uiXq1aiYJlpj5wirKEXNBL/K60gRj20LWlvmFIaO2RgNKCg9ZbkC5LoF5OCAEt9z8RHMWKvAqJU8DNuLwfBISpI8Lll8Zz+/NhhwRU7dk15NWWOgGRQONg="
  on:
    #tags: true
    # temporary workaround for travis issue #1675
    all_branches: true
