language: c 

sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$HOME/miniconda/envs/ci/bin/:$PATH
     # note: mdtraj and coveralls are provided by omnia binstar repo
    - common_py_deps="pip pylint nose python-coveralls cython mdtraj-dev=1.5.0.dev0 matplotlib numpy scipy"
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=17
    - python=3.3  CONDA_PY=33  CONDA_NPY=18
    - python=3.4  CONDA_PY=34  CONDA_NPY=18
    - python=3.4  CONDA_PY=34  CONDA_NPY=19

before_install:
- tools/ci/travis/install_miniconda.sh
- conda config --set always_yes true 
- conda config --add channels http://conda.binstar.org/omnia 
- conda install python-coveralls conda-build jinja2
# use a headless plotting backend for matplotlib
- mkdir -p ~/.config/matplotlib/
- touch ~/.config/matplotlib/matplotlibrc
- "echo 'backend: Agg' >> ~/.config/matplotlib/matplotlibrc"

script:
- conda build tools/conda-recipe
# run pylint (non fatal exit and show only errors)
#- pylint -j 4 --rcfile=.pylintrc pyemma || true

after_success:
- coveralls

